// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sudoku.DataStore;

namespace Sudoku.DataStore.Migrations
{
    [DbContext(typeof(SudokuDbContext))]
    partial class SudokuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sudoku.DataStore.SudokuEntity", b =>
                {
                    b.Property<string>("PuzzleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Clues")
                        .HasColumnType("int");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("Validated")
                        .HasColumnType("int");

                    b.HasKey("PuzzleId");

                    b.ToTable("SudokuPuzzles");
                });
#pragma warning restore 612, 618
        }
    }
}
